### ISSUE TITLE
你好，请问你的模型在ios中应用时，图片采样需要特殊处理吗？目前我在图片缩放采样后，rgb值和android略有差别

### ISSUE THREAD

**Issue by qbshen** [devzwy/open_nsfw_android#13]

**Comment by devzwy** [comment]
同一张图片采集到的RGB值在Android和iOS应该差不是很多，你喂图片前的转换代码方便看一下嘛

**Comment by qbshen** [comment]
-(void)check:(UIImage*)ig block:(void(^)(BOOL valid))block{
    //    int WIDTH = ;
    int INPUTWIDTH = 224;
//    self.iv.image = ig;
    UIImage * scig = [self scaleToSize:ig size:CGSizeMake(256, 256)];
    scig = [self imageFromImage:scig inRect:CGRectMake(16, 16, INPUTWIDTH, INPUTWIDTH)];
    //    self.ivB.image = scig;
    NSString *modelPath = [NSBundle.mainBundle pathForResource:@"nsfw"
                                                        ofType:@"tflite"];
    
    FIRCustomLocalModel *localModel = [[FIRCustomLocalModel alloc] initWithModelPath:modelPath];
    
    
    FIRModelInterpreter * fi = [FIRModelInterpreter modelInterpreterForLocalModel:localModel];
    
    CGImageRef image = scig.CGImage;// Your input image
    long imageWidth = CGImageGetWidth(image);
    long imageHeight = CGImageGetHeight(image);
    
    CGContextRef context = [self createARGBBitmapContextFromImage:image];
    CGContextDrawImage(context, CGRectMake(0, 0, INPUTWIDTH, INPUTWIDTH), image);
    
    UInt8 *imageData = CGBitmapContextGetData(context);
    
    CGContextRelease(context);
    FIRModelInputs *inputs = [[FIRModelInputs alloc] init];
    NSMutableData *inputData = [[NSMutableData alloc] initWithCapacity:0];
    int offs =0;
    for (int row = offs; row < INPUTWIDTH+offs; row++) {
        for (int col = offs; col < INPUTWIDTH+offs; col++) {
            long offset = 4 * (col * INPUTWIDTH + row);
   
            Float32 alph = imageData[offset];
            Float32 red = imageData[offset+1];
            Float32 green = imageData[offset+2];
            Float32 blue = imageData[offset+3];
            Float32 red1 = red - 123;
            Float32 green1 = green - 117;
            Float32 blue1 = blue - 104;
            
            [inputData appendBytes:&blue1 length:sizeof(blue1)];
            [inputData appendBytes:&green1 length:sizeof(green1)];
            [inputData appendBytes:&red1 length:sizeof(red1)];
            
        }
    }
  
    NSError * error = nil;
    [inputs addInput:inputData error:&error];
    
    FIRModelInputOutputOptions *ioOptions = [[FIRModelInputOutputOptions alloc] init];
    [ioOptions setInputFormatForIndex:0
                                 type:FIRModelElementTypeFloat32
                           dimensions:@[@1, @224, @224, @3]
                                error:&error];
    if (error != nil) { return; }
    [ioOptions setOutputFormatForIndex:0
                                  type:FIRModelElementTypeFloat32
                            dimensions:@[@1,@2]
                                 error:&error];
    if (error != nil) { return; }
    [fi runWithInputs:inputs options:ioOptions completion:^(FIRModelOutputs * _Nullable outputs, NSError * _Nullable error) {
        dispatch_async(dispatch_get_main_queue(), ^{
//            NSLog(@"name:%@",name);
            NSArray * ou = [outputs outputAtIndex:0 error:nil];
            //        NSLog(@"%@",ou);
            NSNumber * f = ou[0][0];

            float value = [f floatValue];
            if (block) {
                if (value<=(1-[WVRUserModel sharedInstance].cFriendModel.yellow_score)) {

                    block(NO);
                }else{

                    block(YES);
                }
            }
            
            NSLog(@"%@;%@",ou[0][0], ou[0][1]);
            NSLog(@"e:%@",error);
        });
        
    }];
}


- (UIImage *)scaleToSize:(UIImage *)img size:(CGSize)size{
    // 创建一个bitmap的context
    // 并把它设置成为当前正在使用的context
    UIGraphicsBeginImageContext(size);
    // 绘制改变大小的图片
    [img drawInRect:CGRectMake(0, 0, size.width, size.height)];
    // 从当前context中创建一个改变大小后的图片
    UIImage* scaledImage = UIGraphicsGetImageFromCurrentImageContext();
    // 使当前的context出堆栈
    UIGraphicsEndImageContext();
    // 返回新的改变大小后的图片
    return scaledImage;
}


-(UIImage *)imageFromImage:(UIImage *)image inRect:(CGRect)rect{
    
    //将UIImage转换成CGImageRef
    CGImageRef sourceImageRef = [image CGImage];
    
    //按照给定的矩形区域进行剪裁
    CGImageRef newImageRef = CGImageCreateWithImageInRect(sourceImageRef, rect);
    
    //将CGImageRef转换成UIImage
    UIImage *newImage = [UIImage imageWithCGImage:newImageRef];
    
    //返回剪裁后的图片
    return newImage;
}


- (CGContextRef) createARGBBitmapContextFromImage:(CGImageRef) inImage {
    
    CGContextRef    context = NULL;
    CGColorSpaceRef colorSpace;
    void *          bitmapData;
    int             bitmapByteCount;
    int             bitmapBytesPerRow;
    
    // Get image width, height. We'll use the entire image.
    size_t pixelsWide = CGImageGetWidth(inImage);
    size_t pixelsHigh = CGImageGetHeight(inImage);
    
    // Declare the number of bytes per row. Each pixel in the bitmap in this
    // example is represented by 4 bytes; 8 bits each of red, green, blue, and
    // alpha.
    bitmapBytesPerRow   = (int)(pixelsWide * 4);
    bitmapByteCount     = (int)(bitmapBytesPerRow * pixelsHigh);
    
    // Use the generic RGB color space.
    colorSpace = CGColorSpaceCreateDeviceRGB();
    
    if (colorSpace == NULL)
    {
        fprintf(stderr, "Error allocating color space\n");
        return NULL;
    }
    
    // Allocate memory for image data. This is the destination in memory
    // where any drawing to the bitmap context will be rendered.
    bitmapData = malloc( bitmapByteCount );
    if (bitmapData == NULL)
    {
        fprintf (stderr, "Memory not allocated!");
        CGColorSpaceRelease( colorSpace );
        return NULL;
    }
    
    // Create the bitmap context. We want pre-multiplied ARGB, 8-bits
    // per component. Regardless of what the source image format is
    // (CMYK, Grayscale, and so on) it will be converted over to the format
    // specified here by CGBitmapContextCreate.
    CGImageAlphaInfo alpInfo = CGImageGetAlphaInfo(inImage);
    context = CGBitmapContextCreate (bitmapData,
                                     pixelsWide,
                                     pixelsHigh,
                                     8,      // bits per component
                                     bitmapBytesPerRow,
                                     colorSpace,
                                     alpInfo);
//    kCGImageAlphaNoneSkipFirst
    if (context == NULL)
    {
        free (bitmapData);
        fprintf (stderr, "Context not created!");
    }
    
    // Make sure and release colorspace before returning
    CGColorSpaceRelease( colorSpace );
    
    return context;
}


第一个function是入口，感谢您的回复

**Comment by devzwy** [comment]
如下代码块中的offs变量，你似乎没有给它赋值，默认为0，即从256*256矩阵中取得224*224（横向0开始，纵向也是0开始，这块的取值可以参考下Android端的代码）：
```
int offs =0;
for (int row = offs; row < INPUTWIDTH+offs; row++) {
    for (int col = offs; col < INPUTWIDTH+offs; col++) {
        long offset = 4 * (col * INPUTWIDTH + row);

        Float32 alph = imageData[offset];
        Float32 red = imageData[offset+1];
        Float32 green = imageData[offset+2];
        Float32 blue = imageData[offset+3];
        Float32 red1 = red - 123;
        Float32 green1 = green - 117;
        Float32 blue1 = blue - 104;
        
        [inputData appendBytes:&blue1 length:sizeof(blue1)];
        [inputData appendBytes:&green1 length:sizeof(green1)];
        [inputData appendBytes:&red1 length:sizeof(red1)];
        
    }
}
```
第二个问题，你resize图片的时候，即 原图大小 ->> 256*256 这个过程中，使用的是否为线型差值算法？具体你的框架我不太懂。抱歉。

**Comment by devzwy** [comment]
@qbshen 可以参考这段代码
```
    /**
     * Writes Image data into a `ByteBuffer`.
     */
    private fun convertBitmapToByteBuffer(bitmap_: Bitmap) {
        if (imgData == null || bitmap_ == null) {
            return
        }
        imgData.rewind()
        val W = bitmap_.width
        val H = bitmap_.height

        val w_off = max((W - INPUT_WIDTH) / 2, 0)
        val h_off = max((H - INPUT_HEIGHT) / 2, 0)

        //把每个像素的颜色值转为int 存入intValues
        bitmap_.getPixels(intValues, 0, INPUT_WIDTH, h_off, w_off, INPUT_WIDTH, INPUT_HEIGHT)
        // Convert the image to floating point.
        val startTime = SystemClock.uptimeMillis()
        for (color in intValues) {
            val r1 = Color.red(color)
            val g1 = Color.green(color)
            val b1 = Color.blue(color)

            val rr1 = r1 - 123
            val gg1 = g1 - 117
            val bb1 = b1 - 104

            imgData.putFloat(bb1.toFloat())
            imgData.putFloat(gg1.toFloat())
            imgData.putFloat(rr1.toFloat())
        }
        val endTime = SystemClock.uptimeMillis()
        Log.d(TAG, "Timecost to put values into ByteBuffer: " + (endTime - startTime) + "ms")
    }
```

**Comment by devzwy** [comment]
那我先关了，有问题再开。

**Comment by kakanote** [comment]
你好 请问这个代码里面的文件 在哪里下载 NSString *modelPath = [NSBundle.mainBundle pathForResource:@"nsfw"
                                                    ofType:@"tflite"];

**Comment by devzwy** [comment]
@kakanote [ifLite](https://github.com/devzwy/open_nsfw_android/blob/master/nsfw/src/main/assets/nsfw.tflite)

**Comment by kakanote** [comment]
你好 这个文件在哪里 [WVRUserModel sharedInstance].cFriendModel.yellow_score)

**Comment by kakanote** [comment]
WVRUserModel 这个类 请问在哪里定义的呢

**Comment by davewang** [comment]
我实现了一个ios的demo，有需要的可以去fork
[https://github.com/davewang/open_nsfw_ios](https://github.com/davewang/open_nsfw_ios)

**Comment by xiaohange** [comment]
@qbshen 我也是使用 `TensorFlowLiteObjC`做的, 能否分享一下demo呀? 非常感谢

**Comment by yxzhaoo** [comment]
@xiaohange 
你找到demo了吗

**Comment by xiaohange** [comment]
> @xiaohange
> 你找到demo了吗

只找到作者写的swift版本, oc这种方式需要自己研究
