### ISSUE TITLE
这张图片检测是色情的

### ISSUE THREAD

**Issue by linhaosheng** [devzwy/open_nsfw_android#16]
![WechatIMG389](https://user-images.githubusercontent.com/15604580/79631611-06a3ee80-818d-11ea-9d37-26b606385c67.jpeg)
这张图片检测是色情的

**Comment by devzwy** [comment]
我这边测试是好的，要不你再试试？
<img width="514" alt="截屏2020-04-19 下午7 53 44" src="https://user-images.githubusercontent.com/24636051/79687129-afc71380-8277-11ea-9ba0-82abead4a65a.png">

**Comment by linhaosheng** [comment]
你好，请问您最近有更新模型或者代码吗

**Comment by devzwy** [comment]
Demo更新过，模型不会动了。已经量化过的，没办法优化了。
