### ISSUE TITLE
鉴定值不对

### ISSUE THREAD

**Issue by greadking** [devzwy/open_nsfw_android#2]
![D47VX%(7}Q11Y~J 9H)9I7](https://user-images.githubusercontent.com/26962322/57842781-ca8b3f80-77ff-11e9-91e4-f4305f99056e.jpg)

**Comment by devzwy** [comment]
恩，已经发现这个问题了，正在修改数据。

**Comment by devzwy** [comment]
[Fix](https://github.com/devzwy/open_nsfw_android/releases/tag/1.2.2)
