### ISSUE TITLE
请问23Mb和6MB的模型的差别是什么呀 会有准确率的差别么

### ISSUE THREAD

**Issue by Neonbe** [devzwy/open_nsfw_android#20]

**Comment by devzwy** [comment]
建议用最新版本的模型，老版本模型不支持gpu加速，识别精度影响不大，如果觉得占用空间大的话可以选择使用1.3.4版本，模型文件通过后台下载后初始化。

**Comment by Neonbe** [comment]
![image](https://user-images.githubusercontent.com/24536087/93080516-63fe8600-f6c0-11ea-91db-397fc6b02efd.png)
链接失效了 好像被禁了

**Comment by devzwy** [comment]
晚点我处理一下，感谢反馈。

**Comment by devzwy** [comment]
@Neonbe demo已更新。[README](https://github.com/devzwy/open_nsfw_android)
