### ISSUE TITLE
非androidx项目导入使用报错无法兼容

### ISSUE THREAD

**Issue by chinamingsss** [devzwy/open_nsfw_android#21]
项目没有迁移到androidx还是support，依赖运行不起来报错

**Comment by devzwy** [comment]
内部未使用到support的库，纯代码的，方便的话贴出错误日志看看。

**Comment by chinamingsss** [comment]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-19:19 to override.

**Comment by chinamingsss** [comment]
还有一个问题就是，识别率不行，有的图片识别不了，本身应该是黄色图片

**Comment by devzwy** [comment]
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
> is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
> Suggestion: add 'tools:replace="android:appComponentFactory"' to element at AndroidManifest.xml:5:5-19:19 to override.

[Manifest merger failed](https://blog.csdn.net/zxwd2015/article/details/86651216)

**Comment by devzwy** [comment]
> 还有一个问题就是，识别率不行，有的图片识别不了，本身应该是黄色图片

识别率问题99%以上是分辨率的问题，模糊图片是无法识别的，方便的话图片私信给我，我这边再针对性的测试一下。

**Comment by chinamingsss** [comment]
图片邮箱发给你了，方便加个qq吗？

**Comment by devzwy** [comment]
QQ看的少，微信:admin_zwy

**Comment by chinamingsss** [comment]
加你了
