### ISSUE TITLE
调用鉴黄报错libOpenCL.so

### ISSUE THREAD

**Issue by xiaotian-freedom** [devzwy/open_nsfw_android#23]
Internal error: Failed to run on the given Interpreter: Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found Falling back to OpenGL TfLiteGpuDelegate Invoke: ToTensorConverter: input data size does not match expected size. Node number 90 (TfLiteGpuDelegateV2) failed to invoke.

**Comment by devzwy** [comment]
是华为的机型吗？[参考](https://github.com/tensorflow/tensorflow/issues/35632)

**Comment by xiaotian-freedom** [comment]
bugly统计的机型是“金立 M5”

**Comment by devzwy** [comment]
> bugly统计的机型是“金立 M5”

关闭GPU加速即可。

**Comment by xiaotian-freedom** [comment]
感谢回复！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jason ***@***.***&gt;
发送时间: 2021年5月17日 17:44
收件人: devzwy/open_nsfw_android ***@***.***&gt;
抄送: xiaotian-freedom ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[devzwy/open_nsfw_android] 调用鉴黄报错libOpenCL.so (#23)





  
bugly统计的机型是“金立 M5”
  
关闭GPU加速即可。
