### ISSUE TITLE
提交检测结果不准确的原图

### ISSUE THREAD

**Issue by devzwy** [devzwy/open_nsfw_android#4]
为了更好地使用该库，请您在发现测试结果不准确的图片时提交原图。我会不断的优化。

**Comment by Payphone7** [comment]
我这有个不准确的图，提交到哪呢？

**Comment by devzwy** [comment]
@Payphone7 你就提交到这里就可以呢。谢谢反馈。

**Comment by Payphone7** [comment]
------------------ 原始邮件 ------------------
发件人: "Jason"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 下午2:17
收件人: "devzwy/open_nsfw_android"<open_nsfw_android@noreply.github.com>;
抄送: "许朋朋"<652852743@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [devzwy/open_nsfw_android] 提交检测结果不准确的原图 (#4)




@Payphone7 你就提交到这里就可以呢。谢谢反馈。

**Comment by LiangLuDev** [comment]
![image](https://user-images.githubusercontent.com/16227011/58167608-e179d800-7cbe-11e9-98d9-f8b1ea863bb3.png)
![image](https://user-images.githubusercontent.com/16227011/58167612-e474c880-7cbe-11e9-8f33-fdce7e23ffcc.png)

**Comment by loopq** [comment]
构造确实有点像...

**Comment by devzwy** [comment]
兄弟你这个比基尼是认真的吗😀

**Comment by LiangLuDev** [comment]
@loopq 还真别说 真有点像  哈哈

**Comment by LiangLuDev** [comment]
@devzwy 咱也不知道  咱也不敢问

**Comment by ailala1993929** [comment]
风吹乱雨滴
也吹乱我的心
只一次相遇
却换一生铭记
泪尽一生情
是爱你的宿命
.
.
.

**Comment by Payphone7** [comment]
我那图不好发，太色情了

**Comment by devzwy** [comment]
@Payphone7 dev_zwy@aliyun.com，谢谢反馈。

**Comment by Gurupreet** [comment]
Bro this one is weird should be nsfw!
https://www.google.com/imgres?imgurl=https%3A%2F%2Fcelebxxx.pw%2Fwp-content%2Fuploads%2F2019%2F11%2Fkendall.jpg&imgrefurl=https%3A%2F%2Fcelebxxx.pw%2Fkendall-jenner-completely-naked-photos%2F&tbnid=oYZ3He_cCiYyYM&vet=1&docid=9iV5zK9aLuUPVM&w=748&h=1280&q=nude%20photos&source=sh%2Fx%2Fim

**Comment by Gurupreet** [comment]
Bro this one is swf 0.8 and nsfw 0.2. Can you check
[Image](https://celebxxx.pw/wp-content/uploads/2019/11/kendall.jpg)

**Comment by Gurupreet** [comment]
Bro this one is swf 0.8 and nsfw 0.2. Can you check
[Image](https://celebxxx.pw/wp-content/uploads/2019/11/kendall.jpg)
